# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lubin/deep-embedded-entomology/boards/zyboz7_tcu/hardware/zyboz7_tcu/zyboz7_tcu.srcs/sources_1/bd/zyboz7_tcu/ip/zyboz7_tcu_processing_system7_0_0/zyboz7_tcu_processing_system7_0_0.xci
# IP: The module: 'zyboz7_tcu_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lubin/deep-embedded-entomology/boards/zyboz7_tcu/hardware/zyboz7_tcu/zyboz7_tcu.gen/sources_1/bd/zyboz7_tcu/ip/zyboz7_tcu_processing_system7_0_0/zyboz7_tcu_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zyboz7_tcu_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lubin/deep-embedded-entomology/boards/zyboz7_tcu/hardware/zyboz7_tcu/zyboz7_tcu.srcs/sources_1/bd/zyboz7_tcu/ip/zyboz7_tcu_processing_system7_0_0/zyboz7_tcu_processing_system7_0_0.xci
# IP: The module: 'zyboz7_tcu_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lubin/deep-embedded-entomology/boards/zyboz7_tcu/hardware/zyboz7_tcu/zyboz7_tcu.gen/sources_1/bd/zyboz7_tcu/ip/zyboz7_tcu_processing_system7_0_0/zyboz7_tcu_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zyboz7_tcu_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
