# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Zybo-Z7-Master.xdc

# Block Designs: bd/zyboz7_tcu/zyboz7_tcu.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyboz7_tcu || ORIG_REF_NAME==zyboz7_tcu} -quiet] -quiet

# IP: bd/zyboz7_tcu/ip/zyboz7_tcu_axi_dma_0_0/zyboz7_tcu_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyboz7_tcu_axi_dma_0_0 || ORIG_REF_NAME==zyboz7_tcu_axi_dma_0_0} -quiet] -quiet

# IP: bd/zyboz7_tcu/ip/zyboz7_tcu_axi_gpio_0_0/zyboz7_tcu_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyboz7_tcu_axi_gpio_0_0 || ORIG_REF_NAME==zyboz7_tcu_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zyboz7_tcu/ip/zyboz7_tcu_xbar_0/zyboz7_tcu_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyboz7_tcu_xbar_0 || ORIG_REF_NAME==zyboz7_tcu_xbar_0} -quiet] -quiet

# IP: bd/zyboz7_tcu/ip/zyboz7_tcu_axi_interconnect_0_0/zyboz7_tcu_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyboz7_tcu_axi_interconnect_0_0 || ORIG_REF_NAME==zyboz7_tcu_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/zyboz7_tcu/ip/zyboz7_tcu_proc_sys_reset_0_0/zyboz7_tcu_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyboz7_tcu_proc_sys_reset_0_0 || ORIG_REF_NAME==zyboz7_tcu_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zyboz7_tcu/ip/zyboz7_tcu_processing_system7_0_0/zyboz7_tcu_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyboz7_tcu_processing_system7_0_0 || ORIG_REF_NAME==zyboz7_tcu_processing_system7_0_0} -quiet] -quiet

# IP: bd/zyboz7_tcu/ip/zyboz7_tcu_smartconnect_0_0/zyboz7_tcu_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyboz7_tcu_smartconnect_0_0 || ORIG_REF_NAME==zyboz7_tcu_smartconnect_0_0} -quiet] -quiet

# IP: bd/zyboz7_tcu/ip/zyboz7_tcu_smartconnect_1_0/zyboz7_tcu_smartconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyboz7_tcu_smartconnect_1_0 || ORIG_REF_NAME==zyboz7_tcu_smartconnect_1_0} -quiet] -quiet

# IP: bd/zyboz7_tcu/ip/zyboz7_tcu_smartconnect_2_0/zyboz7_tcu_smartconnect_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyboz7_tcu_smartconnect_2_0 || ORIG_REF_NAME==zyboz7_tcu_smartconnect_2_0} -quiet] -quiet

# IP: bd/zyboz7_tcu/ip/zyboz7_tcu_smartconnect_3_0/zyboz7_tcu_smartconnect_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyboz7_tcu_smartconnect_3_0 || ORIG_REF_NAME==zyboz7_tcu_smartconnect_3_0} -quiet] -quiet

# IP: bd/zyboz7_tcu/ip/zyboz7_tcu_top_zyboz7_0_1/zyboz7_tcu_top_zyboz7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyboz7_tcu_top_zyboz7_0_1 || ORIG_REF_NAME==zyboz7_tcu_top_zyboz7_0_1} -quiet] -quiet

# IP: bd/zyboz7_tcu/ip/zyboz7_tcu_auto_pc_0/zyboz7_tcu_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zyboz7_tcu_auto_pc_0 || ORIG_REF_NAME==zyboz7_tcu_auto_pc_0} -quiet] -quiet

# XDC: /home/lubin/deep-embedded-entomology/boards/zyboz7_tcu/hardware/zyboz7_tcu/zyboz7_tcu.gen/sources_1/bd/zyboz7_tcu/zyboz7_tcu_ooc.xdc
